### ISSUE TITLE
github.com/satori/go.uuid interface change

### ISSUE THREAD

**Issue by tshahmuratov** [heetch/sqalx#11]
Hi. I'm using dep to include sqalx.
Interface of github.com/satori/go.uuid changed and now we have
vendor/github.com/heetch/sqalx/sqalx.go:136:52: not enough arguments in call to uuid.Must
	have (uuid.UUID)
	want (uuid.UUID, error)
Is there any work around here?

**Comment by skateinmars** [comment]
Hello (and sorry for the extra late reply)
We changed the library used for UUIDs to `github.com/rogpeppe/fastuuid` when migrating to go modules, so I will go ahead and close this issue

Thanks for reporting anyway!
