### ISSUE TITLE
used / tested with Gorm

### ISSUE THREAD

**Issue by joeblew99** [heetch/sqalx#3]
this is really useful - thanks for writing this.

Can this be used with GORM (https://github.com/jinzhu/gorm) ?

**Comment by asdine** [comment]
No it's not compatible sorry, but it can pretty easily be done. Gorm already returns the same type when you create a transaction https://godoc.org/github.com/jinzhu/gorm#DB.Begin so basically you can copy paste sqalx code and replace the embedded `Driver` struct by `*gorm.DB` + some minor changes and you're good to go

**Comment by joeblew99** [comment]
ok thanks.  Sounds like a fork of GORM is required, and then a PR back to GORM ?

**Comment by arkan** [comment]
I'm closing this issue. Feel free to reopen it if you still have questions 🤘
